#! /bin/bash
#
# chkconfig: 2345 20 80
# description: Activates/Deactivates OSDVT Server
#

base_dir="/usr/local/osdvt/server/bin"
osdvt="osdvt-server"
port="6970"

start()
{
	! ps -C $osdvt > /dev/null 2> /dev/null && {
	$base_dir/$osdvt >> /usr/local/osdvt/server/log/osdvt-server.log 2>> /usr/local/osdvt/server/log/osdvt-server.log &
        echo -n Starting OSDVT..
	n=120
        while ! ps -C $osdvt > /dev/null 2> /dev/null && [ $n -gt 1 ]; do
                sleep 1
                echo -n .
                n=$(($n - 1))
        done
	sleep 1
        ps -C $osdvt > /dev/null 2> /dev/null && echo -n " OK" ||  echo -n " FAILED"
        echo ""
	} || {
	echo "OSDVT was running."
	}

}

stop()
{
	declare -l option
	ps -C qemu-kvm > /dev/null 2>1 && {
		read -t 5 -p "There is at least one VM running. Kill all VMs? (y/n)" option	
		echo ""
		[ "${option}" == "y" ] && {
			killall qemu-kvm
			n=120
			while ps -C qemu-kvm > /dev/null 2>1 && [ $n -gt 1 ]; do
				sleep 1
                		echo -n .
                		n=$(($n - 1))
			done
			sleep 1
			! ps -C qemu-kvm > /dev/null 2>1 || echo -n " FAILED"
		}
	}
	stop_daemon

}
stop_daemon()
{
	ps -C $osdvt > /dev/null 2> /dev/null && {
	kill $(pidof -x $osdvt) > /dev/null 2> /dev/null
        n=120
        echo -n Stopping OSDVT.. 
        while (ps -C $osdvt > /dev/null 2> /dev/null || netstat -anp | grep ":$port" > /dev/null 2> /dev/null) && [ $n -gt 1 ]; do
                sleep 1
                echo -n .
                n=$(($n - 1))
        done
	sleep 1
        ! ps -C $osdvt > /dev/null 2> /dev/null && echo -n " OK" ||  echo -n " FAILED"
        echo ""
	} || {
	echo "OSDVT is not running."
	}
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
restart)
        stop
        start
        ;;
*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
